# Generated by Django 4.1 on 2022-09-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='task_model',
        ),
    ]
