# Generated by Django 4.1 on 2022-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_task_task_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='creator',
            field=models.CharField(max_length=50),
        ),
    ]
